"""initial schema

Revision ID: 74888db9d937
Revises: 
Create Date: 2026-06-08 15:25:50.092411
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.database  # provides the portable GUID column type


revision: str = '74888db9d937'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role in ('user','admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type in ('income','expense')", name='ck_category_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_category_user_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('auto_save_threshold', sa.Integer(), nullable=False),
    sa.Column('confirm_threshold', sa.Integer(), nullable=False),
    sa.Column('high_value_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=True)

    op.create_table('merchant_mappings',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=160), nullable=False),
    sa.Column('category_id', app.core.database.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'canonical_name', name='uq_merchant_user_name')
    )
    with op.batch_alter_table('merchant_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_mappings_user_id'), ['user_id'], unique=False)

    op.create_table('merchant_learning',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('raw_name', sa.String(length=160), nullable=False),
    sa.Column('merchant_id', app.core.database.GUID(), nullable=False),
    sa.Column('merchant_name', sa.String(length=160), nullable=False),
    sa.Column('category_id', app.core.database.GUID(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('correction_count', sa.Integer(), nullable=False),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('avg_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_max', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hour_histogram', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_mappings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'raw_name', 'merchant_id', name='uq_learning_key')
    )
    with op.batch_alter_table('merchant_learning', schema=None) as batch_op:
        batch_op.create_index('ix_learning_user_raw', ['user_id', 'raw_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_learning_raw_name'), ['raw_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_learning_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('category_id', app.core.database.GUID(), nullable=True),
    sa.Column('raw_merchant', sa.String(length=160), nullable=True),
    sa.Column('merchant_id', app.core.database.GUID(), nullable=True),
    sa.Column('merchant_name', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type in ('income','expense')", name='ck_tx_type'),
    sa.CheckConstraint('amount >= 0', name='ck_tx_amount_nonneg'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_mappings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_tx_user_client')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant_name'), ['merchant_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_raw_merchant'), ['raw_merchant'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference_number'), ['reference_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_tx_user_merchant', ['user_id', 'merchant_name'], unique=False)
        batch_op.create_index('ix_tx_user_occurred', ['user_id', 'occurred_at'], unique=False)

    op.create_table('fraud_alerts',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('transaction_id', app.core.database.GUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraud_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_alerts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_fraud_user_status', ['user_id', 'status'], unique=False)

    op.create_table('merchant_suggestions',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('transaction_id', app.core.database.GUID(), nullable=False),
    sa.Column('raw_name', sa.String(length=160), nullable=False),
    sa.Column('suggested_merchant_id', app.core.database.GUID(), nullable=True),
    sa.Column('suggested_merchant_name', sa.String(length=160), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['suggested_merchant_id'], ['merchant_mappings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchant_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_suggestions_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_suggestions_user_id'), ['user_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('transaction_id', app.core.database.GUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_transaction_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('merchant_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_suggestions_user_id'))
        batch_op.drop_index(batch_op.f('ix_merchant_suggestions_transaction_id'))

    op.drop_table('merchant_suggestions')
    with op.batch_alter_table('fraud_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_fraud_user_status')
        batch_op.drop_index(batch_op.f('ix_fraud_alerts_user_id'))

    op.drop_table('fraud_alerts')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_user_occurred')
        batch_op.drop_index('ix_tx_user_merchant')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference_number'))
        batch_op.drop_index(batch_op.f('ix_transactions_raw_merchant'))
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_name'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('merchant_learning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_learning_user_id'))
        batch_op.drop_index(batch_op.f('ix_merchant_learning_raw_name'))
        batch_op.drop_index('ix_learning_user_raw')

    op.drop_table('merchant_learning')
    with op.batch_alter_table('merchant_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_mappings_user_id'))

    op.drop_table('merchant_mappings')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))

    op.drop_table('settings')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))

    op.drop_table('categories')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
